# Generated by Django 5.0.1 on 2024-04-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='video',
        ),
        migrations.AddField(
            model_name='filmdetails',
            name='thumbnail',
            field=models.FileField(default='thumbnails/tn.jpeg', upload_to='static/thumbnails'),
        ),
        migrations.AddField(
            model_name='filmdetails',
            name='title',
            field=models.CharField(default='movie title', max_length=150),
        ),
    ]
