# Generated by Django 5.0.1 on 2024-04-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_delete_video_filmdetails_thumbnail_filmdetails_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmdetails',
            name='thumbnail',
            field=models.FileField(default='D:\\django_projects\\myprojects\\moviehub\\static\thumbnails\tn.jpeg', upload_to='static/thumbnails'),
        ),
    ]
