# Generated by Django 5.0.3 on 2024-05-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_filmdetails_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmdetails',
            name='thumbnail',
            field=models.FileField(default='thumbnails/tn.jpeg', upload_to='static/thumbnails'),
        ),
    ]
