# Generated by Django 5.0.3 on 2024-05-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_filmdetails_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmdetails',
            name='title',
        ),
        migrations.AddField(
            model_name='filmdetails',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
    ]
