# Generated by Django 5.0.3 on 2024-05-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_remove_filmdetails_title_filmdetails_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmdetails',
            name='ratings',
        ),
        migrations.AddField(
            model_name='filmdetails',
            name='title',
            field=models.CharField(default='movie title', max_length=150),
        ),
    ]
