# Generated by Django 5.0.3 on 2024-05-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_filmdetails_video_shortdesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmdetails',
            name='video_desc',
            field=models.TextField(max_length=500),
        ),
    ]
