# Generated by Django 5.0.3 on 2024-05-12 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_alter_filmdetails_video_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('video_field', models.FileField(upload_to='static/media')),
                ('video_shortDesc', models.TextField(default='video short description', max_length=50)),
                ('video_desc', models.TextField(max_length=500)),
                ('duration', models.CharField(max_length=20)),
                ('released_date', models.DateField()),
                ('thumbnail', models.FileField(default='thumbnails/tn.jpeg', upload_to='static/thumbnails')),
                ('title', models.CharField(default='movie title', max_length=150)),
                ('ratings', models.IntegerField(default=0)),
                ('film_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movie.filmdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Webseries',
            fields=[
                ('video_field', models.FileField(upload_to='static/media')),
                ('video_shortDesc', models.TextField(default='video short description', max_length=50)),
                ('video_desc', models.TextField(max_length=500)),
                ('duration', models.CharField(max_length=20)),
                ('released_date', models.DateField()),
                ('thumbnail', models.FileField(default='thumbnails/tn.jpeg', upload_to='static/thumbnails')),
                ('title', models.CharField(default='movie title', max_length=150)),
                ('ratings', models.IntegerField(default=0)),
                ('film_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movie.filmdetails')),
            ],
        ),
    ]
