# Generated by Django 5.0.3 on 2024-05-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_bollywood_hollywood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bollywood',
            name='thumbnail',
            field=models.FileField(default='thumbnails/tn.jpeg', upload_to='static/Bollywood/thumbnails'),
        ),
        migrations.AlterField(
            model_name='bollywood',
            name='video_field',
            field=models.FileField(upload_to='static/media/Bollywood'),
        ),
        migrations.AlterField(
            model_name='filmdetails',
            name='thumbnail',
            field=models.FileField(default='thumbnails/tn.jpeg', upload_to='static/media/AllFilms/thumbnails'),
        ),
        migrations.AlterField(
            model_name='filmdetails',
            name='video_field',
            field=models.FileField(upload_to='static/media/AllFilms'),
        ),
        migrations.AlterField(
            model_name='hollywood',
            name='thumbnail',
            field=models.FileField(default='thumbnails/tn.jpeg', upload_to='static/Hollywood/thumbnails'),
        ),
        migrations.AlterField(
            model_name='hollywood',
            name='video_field',
            field=models.FileField(upload_to='static/media/Hollwood'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='thumbnail',
            field=models.FileField(default='thumbnails/tn.jpeg', upload_to='static/media/AllMovies/thumbnails'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='video_field',
            field=models.FileField(upload_to='static/media/AllMovies'),
        ),
        migrations.AlterField(
            model_name='webseries',
            name='thumbnail',
            field=models.FileField(default='thumbnails/tn.jpeg', upload_to='static//media/Webseries/thumbnails'),
        ),
        migrations.AlterField(
            model_name='webseries',
            name='video_field',
            field=models.FileField(upload_to='static/media/Webseries'),
        ),
    ]
