# Generated by Django 5.0.3 on 2024-05-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_alter_bollywood_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bollywood',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='bollywood',
            name='released_date',
        ),
        migrations.RemoveField(
            model_name='bollywood',
            name='video_shortDesc',
        ),
        migrations.RemoveField(
            model_name='filmdetails',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='filmdetails',
            name='released_date',
        ),
        migrations.RemoveField(
            model_name='filmdetails',
            name='video_shortDesc',
        ),
        migrations.RemoveField(
            model_name='hollywood',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='hollywood',
            name='released_date',
        ),
        migrations.RemoveField(
            model_name='hollywood',
            name='video_shortDesc',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='released_date',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='video_shortDesc',
        ),
        migrations.RemoveField(
            model_name='webseries',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='webseries',
            name='released_date',
        ),
        migrations.RemoveField(
            model_name='webseries',
            name='video_shortDesc',
        ),
        migrations.AddField(
            model_name='bollywood',
            name='released_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='filmdetails',
            name='released_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='hollywood',
            name='released_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='movies',
            name='released_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='webseries',
            name='released_year',
            field=models.IntegerField(default=2024),
        ),
    ]
