# Generated by Django 5.0.3 on 2024-05-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_alter_filmdetails_video_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmdetails',
            name='video_field',
            field=models.FileField(max_length=500, upload_to='static/media/AllFilms'),
        ),
    ]
